"use client";
import { ChangeEvent, FormEvent, useCallback, useEffect, useState } from "react";
import { Link } from "@/components/Link";
import { Download, FileSearch, MessageCircle, Plus, RefreshCw, Settings2, UploadCloud, Users } from "lucide-react";
import { api } from "@/lib/api";
import { session } from "@/lib/session";
import { candidateWhatsAppUrl } from "@/lib/whatsapp";
import { Busy, Notice, PortalShell, StatusPill } from "@/components/portal/PortalShell";

const blank={fullName:"",email:"",phone:"",position:"",college:"",qualification:"",validityHours:168,singleUse:false};
export default function AdminDashboard(){const [dashboard,setDashboard]=useState<any>(null);const [candidates,setCandidates]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [success,setSuccess]=useState("");const [tab,setTab]=useState("candidates");const [query,setQuery]=useState("");const [form,setForm]=useState<any>(blank);const [created,setCreated]=useState<any>(null);const [file,setFile]=useState<File|null>(null);const [position,setPosition]=useState("");const [preview,setPreview]=useState<any>(null);const [results,setResults]=useState<any[]>([]);const [settings,setSettings]=useState<any>(null);const [working,setWorking]=useState(false);
  const logout=()=>{session.clearAdmin();window.location.replace("/admin/login")};
  const load=useCallback(async()=>{if(!session.get("admin")){window.location.replace("/admin/login");return}setLoading(true);setError("");try{const [dash,list]=await Promise.all([api.adminDashboard(),api.adminCandidates("limit=100")]);setDashboard(dash);setCandidates(list.candidates||[])}catch(reason:any){if(reason.status===401)logout();else setError(reason.message)}finally{setLoading(false)}},[]);
  useEffect(()=>{load()},[load]);
  async function search(){setWorking(true);try{const result=await api.adminCandidates(`limit=100&q=${encodeURIComponent(query)}`);setCandidates(result.candidates||[])}catch(reason:any){setError(reason.message)}finally{setWorking(false)}}
  async function create(event:FormEvent){event.preventDefault();setWorking(true);setError("");setSuccess("");try{const result=await api.createCandidate({...form,validityHours:Number(form.validityHours)});setCreated(result);setSuccess(`Candidate created. Email delivery: ${result.invitation.emailDelivery?.status||"QUEUED"}.`);setForm(blank);await load()}catch(reason:any){setError(reason.message)}finally{setWorking(false)}}
  async function scan(){if(!file)return;setWorking(true);setError("");try{const result=await api.scanCandidates(file,position);setPreview(result.preview);setResults([])}catch(reason:any){setError(reason.message)}finally{setWorking(false)}}
  async function importRows(){if(!preview)return;setWorking(true);setError("");try{const rows=preview.rows.filter((row:any)=>row.valid).map(({rowNumber,valid,errors,...row}:any)=>row);const result=await api.importCandidates({rows,validityHours:168,singleUse:false});setResults(result.results||[]);setSuccess(`${result.summary.created} candidates created. Each existing email notification was attempted independently.`);await load()}catch(reason:any){setError(reason.message)}finally{setWorking(false)}}
  async function openSettings(){setTab("settings");if(!settings){try{const result=await api.settings();setSettings(result.settings)}catch(reason:any){setError(reason.message)}}}
  async function saveSettings(event:FormEvent){event.preventDefault();setWorking(true);setError("");try{const numeric={...settings,durationMinutes:Number(settings.durationMinutes),maxQuestions:Number(settings.maxQuestions),recordingRetentionDays:Number(settings.recordingRetentionDays),weights:Object.fromEntries(Object.entries(settings.weights).map(([key,value])=>[key,Number(value)]))};await api.updateSettings(numeric);setSuccess("Interview defaults saved for future interviews.")}catch(reason:any){setError(reason.message)}finally{setWorking(false)}}
  if(loading)return <PortalShell role="admin" onLogout={logout}><Busy label="Loading live hiring intelligence…"/></PortalShell>;
  const totals=dashboard?.totals||{};
  return <PortalShell role="admin" onLogout={logout}><div className="portal-header"><div><span className="section-kicker">Administration workspace</span><h1>Hiring intelligence,<br/><span className="gradient-text">in one command centre.</span></h1><p>Candidate hierarchy, invitations, evidence and decisions stay connected.</p></div><button className="btn" onClick={load}><RefreshCw size={15}/>Refresh live data</button></div>
    <div className="metric-grid">{[["All candidates",totals.total||0],["Live interviews",totals.liveInterviews||0],["Completed",totals.interviewsCompleted||0],["Selected",totals.selected||0]].map(([label,value])=><div className="metric-card" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
    <div className="tabs"><button className={`tab ${tab==="candidates"?"active":""}`} onClick={()=>setTab("candidates")}><Users size={13}/> Candidate hierarchy</button><button className={`tab ${tab==="create"?"active":""}`} onClick={()=>setTab("create")}><Plus size={13}/> Add candidate</button><button className={`tab ${tab==="bulk"?"active":""}`} onClick={()=>setTab("bulk")}><UploadCloud size={13}/> Smart bulk scanner</button><button className={`tab ${tab==="settings"?"active":""}`} onClick={openSettings}><Settings2 size={13}/> Interview settings</button></div>{error&&<Notice kind="error">{error}</Notice>}{success&&<Notice kind="success">{success}</Notice>}
    {tab==="candidates"&&<section className="panel"><div className="tool-row"><div className="field"><label>Search candidates</label><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()} placeholder="Name, email or phone"/></div><button className="btn" onClick={search} disabled={working}>Search</button><button className="btn" onClick={()=>window.print()}><Download size={14}/>Print / save PDF</button></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Candidate</th><th>Email / phone</th><th>Position</th><th>Invitation</th><th>Status</th><th>AI score</th><th>Actions</th></tr></thead><tbody>{candidates.map(candidate=>{const whatsapp=candidateWhatsAppUrl(candidate,candidate.invitation);return <tr key={candidate.id}><td><Link href={`/admin/candidate/${candidate.id}`}>{candidate.fullName}</Link></td><td>{candidate.email}<br/><span style={{color:"#7586a8"}}>{candidate.phone}</span></td><td>{candidate.position||"—"}</td><td>{candidate.invitation?.code||"—"}<br/><small>{candidate.invitation?.emailDelivery?.status||""}</small></td><td><StatusPill value={candidate.status}/></td><td>{candidate.aiScore??"—"}</td><td><div className="tool-row" style={{margin:0,flexWrap:"nowrap"}}><Link className="btn" href={`/admin/candidate/${candidate.id}`}>View</Link>{whatsapp&&<button className="btn icon-btn" title="Open pre-filled WhatsApp message" onClick={()=>window.open(whatsapp,"_blank","noopener,noreferrer")}><MessageCircle size={16}/></button>}</div></td></tr>})}</tbody></table></div></section>}
    {tab==="create"&&<div className="portal-grid two"><form className="panel form-grid" onSubmit={create}><h2>Add one candidate</h2><div className="form-grid two"><div className="field"><label>Full name</label><input value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} required/></div><div className="field"><label>Email</label><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></div><div className="field"><label>Phone / WhatsApp</label><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="+91 98765 43210" required/></div><div className="field"><label>Position</label><input value={form.position} onChange={e=>setForm({...form,position:e.target.value})}/></div><div className="field"><label>College</label><input value={form.college} onChange={e=>setForm({...form,college:e.target.value})}/></div><div className="field"><label>Qualification</label><input value={form.qualification} onChange={e=>setForm({...form,qualification:e.target.value})}/></div></div><div className="field"><label>Invitation validity (hours)</label><input type="number" min="1" max="2160" value={form.validityHours} onChange={e=>setForm({...form,validityHours:e.target.value})}/></div><label style={{fontSize:12,color:"#aab7d4"}}><input type="checkbox" checked={form.singleUse} onChange={e=>setForm({...form,singleUse:e.target.checked})}/> Single-use invitation</label><button className="btn btn-primary" disabled={working}>{working?"Creating and sending email…":"Create candidate & email invitation"}</button></form><section className="panel"><h2>Notification flow</h2><p className="panel-subtitle">The existing transactional email system is unchanged. Creating a candidate automatically attempts the invitation email with code, interview time guidance, warnings and terms.</p><Notice>WhatsApp is an additional free Click-to-Chat action only. It prepares the candidate-specific message; an administrator reviews it and manually taps Send in WhatsApp.</Notice>{created&&<div style={{marginTop:18}}><StatusPill value={created.invitation.emailDelivery?.status}/><h3>{created.candidate.fullName}</h3><p className="panel-subtitle">Invitation code: <b>{created.invitation.code}</b></p><button className="btn" onClick={()=>window.open(candidateWhatsAppUrl(created.candidate,created.invitation),"_blank","noopener,noreferrer")}><MessageCircle size={15}/>Open WhatsApp message</button></div>}</section></div>}
    {tab==="bulk"&&<div className="portal-grid sidebar"><section className="panel"><FileSearch size={27} color="#60cdff"/><h2 style={{marginTop:20}}>Smart scanner</h2><p className="panel-subtitle">Accepted: Excel (.xlsx), CSV, PDF, Word (.doc/.docx), screenshot or clear photo. Maximum 500 candidates per file.</p><Notice>Use one candidate per row. Recommended columns: Serial, Full Name, Email, Phone/WhatsApp, Position, College, Qualification. Email and phone must belong to the same person; the preview lets you verify every row before import.</Notice><div className="field" style={{marginTop:15}}><label>Default position (optional)</label><input value={position} onChange={e=>setPosition(e.target.value)}/></div><div className="field"><label>Candidate file</label><input type="file" accept=".xlsx,.csv,.pdf,.doc,.docx,image/*" onChange={(e:ChangeEvent<HTMLInputElement>)=>setFile(e.target.files?.[0]||null)}/></div><button className="btn btn-primary" onClick={scan} disabled={!file||working}>{working?"Scanning securely…":"Scan & build preview"}</button></section><section className="panel"><h2>Candidate-specific preview</h2>{preview?<><p className="panel-subtitle">{preview.fileName}: {preview.valid} valid · {preview.invalid} need attention</p><div className="bulk-preview">{preview.rows.map((row:any)=><div className={`bulk-row ${row.valid?"":"invalid"}`} key={`${row.rowNumber}-${row.email}`}><b>{row.serial||row.rowNumber}</b><span>{row.fullName}</span><span>{row.email}</span><span>{row.phone}</span><StatusPill value={row.valid?"READY":"FIX"}/>{!row.valid&&<small style={{gridColumn:"2/-1",color:"#ff9eb6"}}>{row.errors.join(" · ")}</small>}</div>)}</div><button className="btn btn-primary" style={{marginTop:16}} onClick={importRows} disabled={!preview.valid||working}>{working?"Creating individual invitations…":`Import ${preview.valid} valid candidates`}</button></>:<p className="panel-subtitle">Upload and scan a file to verify that each name, email and phone stay on the correct row.</p>}{results.length>0&&<div style={{marginTop:20}}><h3>Import results</h3>{results.map((item:any,index)=><div className="qa" key={index} style={{marginTop:8}}><StatusPill value={item.status}/><b style={{marginLeft:10}}>{item.candidate?.fullName||item.input?.fullName||item.serial}</b>{item.status==="CREATED"&&<button className="btn" style={{marginLeft:10}} onClick={()=>window.open(candidateWhatsAppUrl(item.candidate,item.invitation),"_blank","noopener,noreferrer")}><MessageCircle size={14}/>WhatsApp</button>}{item.error&&<p>{item.error}</p>}</div>)}</div>}</section></div>}
    {tab==="settings"&&<form className="panel form-grid" onSubmit={saveSettings}>{settings?<><h2>Interview defaults</h2><p className="panel-subtitle">These settings apply only to future interview attempts.</p><div className="form-grid two"><div className="field"><label>Duration (minutes)</label><input type="number" min="5" max="60" value={settings.durationMinutes} onChange={e=>setSettings({...settings,durationMinutes:e.target.value})}/></div><div className="field"><label>Maximum questions</label><input type="number" min="5" max="30" value={settings.maxQuestions} onChange={e=>setSettings({...settings,maxQuestions:e.target.value})}/></div><div className="field"><label>Recording retention (days)</label><input type="number" min="1" max="365" value={settings.recordingRetentionDays} onChange={e=>setSettings({...settings,recordingRetentionDays:e.target.value})}/></div></div><label style={{fontSize:12}}><input type="checkbox" checked={settings.adaptiveDifficulty} onChange={e=>setSettings({...settings,adaptiveDifficulty:e.target.checked})}/> Adaptive difficulty</label><h3>Evidence weights (must total 100)</h3><div className="form-grid two">{Object.entries(settings.weights).map(([key,value])=><div className="field" key={key}><label>{key} %</label><input type="number" min="0" max="100" value={String(value)} onChange={e=>setSettings({...settings,weights:{...settings.weights,[key]:e.target.value}})}/></div>)}</div><button className="btn btn-primary" disabled={working}>Save future interview defaults</button></>:<p>Loading settings…</p>}</form>}
  </PortalShell>}
