"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowRight, Mic, MicOff, RotateCcw, Send, ShieldCheck, Video } from "lucide-react";
import { api } from "@/lib/api";
import { session } from "@/lib/session";
import { Notice, PortalShell, StatusPill } from "@/components/portal/PortalShell";

type Question={id:string;sequence:number;text:string;category:string;difficulty:string};
type SpeechRecognitionLike={continuous:boolean;interimResults:boolean;lang:string;start:()=>void;stop:()=>void;abort:()=>void;onresult:((event:any)=>void)|null;onend:(()=>void)|null;onerror:((event:any)=>void)|null};
declare global { interface Window { SpeechRecognition?:new()=>SpeechRecognitionLike; webkitSpeechRecognition?:new()=>SpeechRecognitionLike; } }

const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
async function retry<T>(task:()=>Promise<T>, attempts=4){let last:any;for(let index=0;index<attempts;index++){try{return await task()}catch(error){last=error;if(index<attempts-1)await sleep(900*2**index)}}throw last}
function mimeType(){for(const type of ["video/webm;codecs=vp8,opus","video/webm","video/mp4"]){if(typeof MediaRecorder!=="undefined"&&MediaRecorder.isTypeSupported(type))return type}return ""}

export default function CandidateInterview(){const videoRef=useRef<HTMLVideoElement>(null);const streamRef=useRef<MediaStream|null>(null);const recorderRef=useRef<MediaRecorder|null>(null);const chunksRef=useRef<Blob[]>([]);const recognitionRef=useRef<SpeechRecognitionLike|null>(null);const listeningWanted=useRef(false);const startedAt=useRef(0);const silenceTimerRef=useRef<ReturnType<typeof setTimeout>|null>(null);const questionRef=useRef<Question|null>(null);const answerRef=useRef("");const interimRef=useRef("");const busyRef=useRef(false);
  const [phase,setPhase]=useState<"consent"|"interview"|"upload"|"done">("consent");const [question,setQuestion]=useState<Question|null>(null);const [interviewId,setInterviewId]=useState("");const [answer,setAnswer]=useState("");const [interim,setInterim]=useState("");const [voiceUsed,setVoiceUsed]=useState(false);const [listening,setListening]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [warning,setWarning]=useState("");const [progress,setProgress]=useState(0);const [consent,setConsent]=useState({recording:false,camera:false,microphone:false,monitoring:false});
  const logout=()=>{session.clearCandidate();window.location.replace("/candidate/login")};
  const clearSilenceTimer=useCallback(()=>{if(silenceTimerRef.current!==null){clearTimeout(silenceTimerRef.current);silenceTimerRef.current=null}},[]);
  const stopSpeech=useCallback(()=>{listeningWanted.current=false;recognitionRef.current?.stop();setListening(false)},[]);
  const startSpeech=useCallback(()=>{const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){setWarning("Live speech recognition is not available in this browser. Your microphone and recording remain active; type the answer below.");return}if(!recognitionRef.current){const recognition=new Recognition();recognition.continuous=true;recognition.interimResults=true;recognition.lang="en-IN";recognition.onresult=(event:any)=>{let finalText="";let live="";for(let i=event.resultIndex;i<event.results.length;i++){const text=event.results[i][0].transcript;if(event.results[i].isFinal)finalText+=text;else live+=text}if(finalText){clearSilenceTimer();const merged=`${answerRef.current} ${finalText}`.trim();answerRef.current=merged;setAnswer(merged);setVoiceUsed(true)}if(live){clearSilenceTimer();interimRef.current=live}setInterim(live)};recognition.onerror=(event:any)=>{if(event.error!=="no-speech"){setWarning(`Speech service reported ${event.error}. Recording is still active; you can continue or type your answer.`)}};recognition.onend=()=>{setListening(false);if(listeningWanted.current)setTimeout(()=>{try{recognition.start();setListening(true)}catch{}},350)};recognitionRef.current=recognition}listeningWanted.current=true;try{recognitionRef.current.start();setListening(true);setWarning("")}catch{}},[clearSilenceTimer]);
  const speakQuestion=useCallback((text:string,onReady:()=>void)=>{if("speechSynthesis"in window){speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.rate=.92;utterance.onend=()=>{startSpeech();onReady()};speechSynthesis.speak(utterance)}else{startSpeech();onReady()}},[startSpeech]);
  useEffect(()=>{questionRef.current=question;answerRef.current=answer;interimRef.current=interim;busyRef.current=busy},[question,answer,interim,busy]);
  useEffect(()=>{if(answer.trim()||interim.trim())clearSilenceTimer()},[answer,interim,clearSilenceTimer]);
  useEffect(()=>{if(!session.get("interview")){window.location.replace("/candidate/login");return}const visibility=()=>{if(document.hidden&&interviewId){setWarning("Do not leave the interview window. This event has been recorded for the administrator.");api.event(interviewId,{type:"APP_BACKGROUND",metadata:{source:"web"}}).catch(()=>{})}};const before=(event:BeforeUnloadEvent)=>{if(phase==="interview"||phase==="upload"){event.preventDefault();event.returnValue="Your protected recording is still in progress."}};document.addEventListener("visibilitychange",visibility);window.addEventListener("beforeunload",before);return()=>{document.removeEventListener("visibilitychange",visibility);window.removeEventListener("beforeunload",before);clearSilenceTimer();stopSpeech();speechSynthesis?.cancel()}},[interviewId,phase,stopSpeech,clearSilenceTimer]);
  useEffect(()=>()=>{streamRef.current?.getTracks().forEach(track=>track.stop())},[]);
  useEffect(()=>{
    if(phase==="interview"&&videoRef.current&&streamRef.current){
      videoRef.current.srcObject=streamRef.current;
      videoRef.current.play().catch(()=>{});
    }
  },[phase]);
  function armSilenceSkip(questionId:string){clearSilenceTimer();silenceTimerRef.current=setTimeout(()=>{const activeQuestion=questionRef.current;if(!activeQuestion||activeQuestion.id!==questionId||busyRef.current||answerRef.current.trim()||interimRef.current.trim())return;void skipSilentQuestion(questionId)},20_000)}
  async function askNext(nextQuestion:Question,delay=350){setQuestion(nextQuestion);setTimeout(()=>speakQuestion(nextQuestion.text,()=>armSilenceSkip(nextQuestion.id)),delay)}
  async function skipSilentQuestion(questionId:string){const activeQuestion=questionRef.current;if(!activeQuestion||activeQuestion.id!==questionId||busyRef.current||answerRef.current.trim()||interimRef.current.trim())return;clearSilenceTimer();busyRef.current=true;setBusy(true);setError("");stopSpeech();speechSynthesis?.cancel();try{const result=await api.submitAnswer(interviewId,{questionId,transcript:"No response recorded — automatically skipped after 20 seconds of silence.",source:"MANUAL"},crypto.randomUUID());setWarning("No voice or typed answer was detected in 20 seconds. This question was skipped.");answerRef.current="";interimRef.current="";setAnswer("");setInterim("");setVoiceUsed(false);if(result.completed){setQuestion(null);await finishRecording(interviewId)}else await askNext(result.currentQuestion)}catch(reason:any){setError(reason.message||"The unanswered question could not be skipped. You can continue or retry.");startSpeech()}finally{busyRef.current=false;setBusy(false)}}
  async function begin(){if(!Object.values(consent).every(Boolean))return;setBusy(true);setError("");try{if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==="undefined")throw new Error("This browser cannot securely record camera and microphone. Use current Chrome, Edge or Safari.");const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:1280},height:{ideal:720}},audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});streamRef.current=stream;if(videoRef.current)videoRef.current.srcObject=stream;const type=mimeType();const recorder=new MediaRecorder(stream,type?{mimeType:type,videoBitsPerSecond:1_800_000,audioBitsPerSecond:96_000}:undefined);chunksRef.current=[];recorder.ondataavailable=event=>{if(event.data.size)chunksRef.current.push(event.data)};recorder.onerror=()=>{setWarning("Recording was interrupted. Keep this page open while automatic recovery runs.");if(interviewId)api.event(interviewId,{type:"RECORDING_INTERRUPTION",metadata:{source:"web"}}).catch(()=>{})};recorderRef.current=recorder;recorder.start(3000);startedAt.current=Date.now();const result=await api.startInterview();setInterviewId(result.interview.id);setQuestion(result.currentQuestion);setPhase("interview");if(result.completed){await finishRecording(result.interview.id);return}setTimeout(()=>speakQuestion(result.currentQuestion.text,()=>armSilenceSkip(result.currentQuestion.id)),450)}catch(reason:any){streamRef.current?.getTracks().forEach(track=>track.stop());setError(reason.message||"Camera and microphone could not start.")}finally{setBusy(false)}}
  async function submit(){if(!question||!answer.trim()||busy)return;clearSilenceTimer();setBusy(true);setError("");stopSpeech();speechSynthesis?.cancel();try{const result=await api.submitAnswer(interviewId,{questionId:question.id,transcript:answer.trim(),transcriptConfidence:voiceUsed?0.82:undefined,source:voiceUsed?"SPEECH":"MANUAL"},crypto.randomUUID());answerRef.current="";interimRef.current="";setAnswer("");setInterim("");setVoiceUsed(false);if(result.completed){setQuestion(null);await finishRecording(interviewId)}else await askNext(result.currentQuestion)}catch(reason:any){setError(reason.message||"Your answer could not be submitted. It remains on this screen so you can retry.");startSpeech()}finally{setBusy(false)}}
  async function finishRecording(id:string){setPhase("upload");stopSpeech();speechSynthesis?.cancel();const recorder=recorderRef.current;const stopped=new Promise<void>(resolve=>{if(!recorder||recorder.state==="inactive")resolve();else{const previous=recorder.onstop;recorder.onstop=(event)=>{previous?.call(recorder,event);resolve()};recorder.requestData();recorder.stop()}});await stopped;streamRef.current?.getTracks().forEach(track=>track.stop());const blob=new Blob(chunksRef.current,{type:recorder?.mimeType||"video/webm"});if(!blob.size){setError("The browser did not produce a recording. Keep this page open and contact the administrator.");return}const chunkSize=2*1024*1024;const total=Math.ceil(blob.size/chunkSize);try{for(let index=0;index<total;index++){const part=blob.slice(index*chunkSize,Math.min(blob.size,(index+1)*chunkSize),blob.type);await retry(()=>api.uploadChunk(id,part,index,total,blob.size));setProgress(Math.round(((index+1)/total)*92))}await retry(()=>api.finalizeRecording(id,Math.max(1,Math.round((Date.now()-startedAt.current)/1000))),5);setProgress(100);setPhase("done");setTimeout(()=>window.location.replace("/candidate"),1200)}catch(reason:any){setError(reason.message||"Protected upload paused. Your recording is still held on this page. Tap retry without closing it.");setWarning("Do not close or refresh this page until recording upload reaches 100%.")}}
  async function retryUpload(){if(!interviewId)return;setBusy(true);setError("");try{await finishRecording(interviewId)}finally{setBusy(false)}}
  if(phase==="consent")return <PortalShell role="candidate" onLogout={logout}><div className="portal-header"><div><span className="section-kicker">Protected web interview</span><h1>Ready when <span className="gradient-text">you are.</span></h1><p>Review every requirement before camera and microphone access begins.</p></div></div><div className="portal-grid sidebar"><section className="panel"><ShieldCheck size={28} color="#68d7ff"/><h2 style={{marginTop:25}}>Consent and readiness</h2><p className="panel-subtitle">Your video, microphone, submitted answers and interview-integrity events will be securely recorded and shown to authorized administrators. You can review your recording and report in your candidate profile.</p>{Object.entries({recording:"I consent to video and audio recording",camera:"I allow camera access",microphone:"I allow microphone access",monitoring:"I understand interview integrity monitoring"}).map(([key,label])=><label key={key} style={{display:"flex",gap:10,alignItems:"flex-start",margin:"16px 0",fontSize:13,color:"#c5d0e7"}}><input type="checkbox" checked={consent[key as keyof typeof consent]} onChange={e=>setConsent({...consent,[key]:e.target.checked})}/>{label}</label>)}{error&&<Notice kind="error">{error}</Notice>}<button className="btn btn-primary" disabled={!Object.values(consent).every(Boolean)||busy} onClick={begin}><Video size={16}/>{busy?"Starting secure devices…":"Start protected interview"}</button></section><section className="panel"><h2>Before you begin</h2><div className="check-list"><span>• Use current Chrome, Edge or Safari.</span><span>• Keep your face visible and use bright, even light.</span><span>• Use stable Wi-Fi and connect your charger.</span><span>• Do not close, refresh or switch away during upload.</span><span>• Speak naturally; you can always type if speech recognition pauses.</span></div><Notice>Browser speech recognition helps create your transcript. The protected audio recording continues independently even when live transcription pauses.</Notice></section></div></PortalShell>;
  return <PortalShell role="candidate" onLogout={logout}><div className="portal-header"><div><span className="section-kicker">Live AI interview</span><h1>{phase==="interview"?"Your answer,":"Securing your"} <span className="gradient-text">{phase==="interview"?"your evidence.":"recording."}</span></h1><p>{phase==="interview"?"Camera and microphone recording remain active across every question.":"Keep this page open until the protected upload reaches 100%."}</p></div>{phase==="interview"&&<span className="recording-dot"><i/> RECORDING</span>}</div>{warning&&<Notice>{warning}</Notice>}{error&&<Notice kind="error">{error}</Notice>}
    {phase==="interview"?<div className="interview-stage"><section className="panel question-card"><div>{question&&<><StatusPill value={`Question ${question.sequence} · ${question.category} · ${question.difficulty}`}/><h1>{question.text}</h1></>}</div><div><div className="field"><label>Live answer transcript</label><textarea className="transcript-box" value={`${answer}${interim?` ${interim}`:""}`} onChange={e=>{clearSilenceTimer();answerRef.current=e.target.value;interimRef.current="";setAnswer(e.target.value);setInterim("")}} placeholder="Speak your answer or type here…"/></div><p className="panel-subtitle" style={{marginTop:10}}>If no voice or typed answer is detected within 20 seconds after the question is read, it will be skipped automatically.</p><div className="tool-row" style={{margin:"14px 0 0"}}><button className={`btn ${listening?"btn-primary":""}`} onClick={listening?stopSpeech:startSpeech}>{listening?<MicOff size={16}/>:<Mic size={16}/>} {listening?"Pause live transcript":"Resume microphone transcript"}</button><button className="btn btn-primary" onClick={submit} disabled={busy||!answer.trim()}>{busy?"Evaluating…":<>Submit & next <Send size={15}/></>}</button></div></div></section><aside className="panel"><video ref={videoRef} className="live-camera" autoPlay muted playsInline/><div className="candidate-meta"><span className="recording-dot"><i/> Video + audio protected</span></div><p className="panel-subtitle">A speech-transcript pause does not stop your audio/video recording. Use the button to resume live text.</p></aside></div>:<section className="panel" style={{maxWidth:760,margin:"0 auto",textAlign:"center"}}><div className="intro-core" style={{width:72,margin:"0 auto 26px"}}/><h2>{phase==="done"?"Recording secured":"Uploading protected recording"}</h2><p className="panel-subtitle">{progress}% complete. Your answers are already saved; video and audio are now being attached to the same candidate record.</p><div className="upload-progress"><i style={{width:`${progress}%`}}/></div>{error&&<button className="btn btn-primary" style={{marginTop:20}} onClick={retryUpload} disabled={busy}><RotateCcw size={15}/>Retry protected upload</button>}{phase==="done"&&<a className="btn" style={{marginTop:20}} href="/candidate">Open my interview profile <ArrowRight size={15}/></a>}</section>}
  </PortalShell>}
