export const CandidateStatus = Object.freeze({
  INVITED: "INVITED",
  RESUME_PENDING: "RESUME_PENDING",
  READY_FOR_INTERVIEW: "READY_FOR_INTERVIEW",
  INTERVIEW_IN_PROGRESS: "INTERVIEW_IN_PROGRESS",
  INTERVIEW_COMPLETED: "INTERVIEW_COMPLETED",
  UNDER_REVIEW: "UNDER_REVIEW",
  SELECTED: "SELECTED",
  REJECTED: "REJECTED",
  HOLD: "HOLD",
  REINTERVIEW_REQUIRED: "REINTERVIEW_REQUIRED"
});

export const InterviewStatus = Object.freeze({
  READY: "READY",
  IN_PROGRESS: "IN_PROGRESS",
  PROCESSING: "PROCESSING",
  COMPLETED: "COMPLETED",
  TERMINATED: "TERMINATED",
  RECOVERY_REQUIRED: "RECOVERY_REQUIRED"
});

export const InterviewState = Object.freeze({
  IDLE: "IDLE",
  INITIALIZING: "INITIALIZING",
  AI_SPEAKING: "AI_SPEAKING",
  WAITING_FOR_ANSWER: "WAITING_FOR_ANSWER",
  LISTENING: "LISTENING",
  TRANSCRIBING: "TRANSCRIBING",
  ANALYZING: "ANALYZING",
  GENERATING_NEXT: "GENERATING_NEXT",
  WARNING: "WARNING",
  FINISHING: "FINISHING",
  COMPLETED: "COMPLETED",
  ERROR: "ERROR"
});

export const ApiErrorCode = Object.freeze({
  INVALID_INVITATION: "INVALID_INVITATION",
  INVITATION_EXPIRED: "INVITATION_EXPIRED",
  INVITATION_REVOKED: "INVITATION_REVOKED",
  INVITATION_LOCKED: "INVITATION_LOCKED",
  INTERVIEW_TERMINATED: "INTERVIEW_TERMINATED",
  AI_UNAVAILABLE: "AI_UNAVAILABLE",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT"
});
