"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { ArrowLeft, Download, MessageCircle, RefreshCw, RotateCcw } from "lucide-react";
import { Link } from "@/components/Link";
import { api } from "@/lib/api";
import { session } from "@/lib/session";
import { candidateWhatsAppUrl } from "@/lib/whatsapp";
import { Busy, Notice, PortalShell, StatusPill } from "@/components/portal/PortalShell";

function summary(value:any){if(!value)return "AI assessment has not been generated yet.";if(typeof value==="string")return value;return value.summary||value.overallSummary||value.recommendationRationale||Object.values(value).filter(item=>typeof item==="string").join(" ")||"Assessment available in evidence fields below."}
export default function CandidateEvaluation(){const {id}=useParams<{id:string}>();const [data,setData]=useState<any>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [success,setSuccess]=useState("");const [media,setMedia]=useState("");const [decision,setDecision]=useState("HOLD");const [comment,setComment]=useState("");const [feedback,setFeedback]=useState("");const [working,setWorking]=useState(false);
  const logout=()=>{session.clearAdmin();window.location.replace("/admin/login")};const load=useCallback(async()=>{if(!session.get("admin")){logout();return}setLoading(true);setError("");try{const result=await api.adminCandidate(String(id));setData(result);if(result.adminDecision){setDecision(result.adminDecision.decision);setComment(result.adminDecision.comment||"");setFeedback(result.adminDecision.candidateFeedback||"")}}catch(reason:any){if(reason.status===401)logout();else setError(reason.message)}finally{setLoading(false)}},[id]);useEffect(()=>{load()},[load]);
  useEffect(()=>{let objectUrl="";(async()=>{if(data?.recording?.status==="READY"&&data?.interview?._id){try{objectUrl=await api.protectedMedia(`/api/admin/interviews/${data.interview._id}/recording`,session.get("admin"));setMedia(objectUrl)}catch(reason:any){setError(reason.message)}}})();return()=>{if(objectUrl)URL.revokeObjectURL(objectUrl)}},[data?.recording?.status,data?.interview?._id]);
  const scores=useMemo(()=>Object.entries(data?.interview?.scores||{}).filter(([,value])=>typeof value==="number"),[data]);
  async function saveDecision(event:FormEvent){event.preventDefault();if(!data?.interview?._id)return;setWorking(true);setError("");try{await api.decide(data.interview._id,{decision,comment,candidateFeedback:feedback});setSuccess("Decision saved. Candidate-facing feedback is now visible in the candidate profile.");await load()}catch(reason:any){setError(reason.message)}finally{setWorking(false)}}
  async function reset(){setWorking(true);setError("");try{const result=await api.resetInvitation(String(id));setSuccess(`New code ${result.invitation.code} created. Email delivery: ${result.invitation.emailDelivery?.status||"PENDING"}.`);await load()}catch(reason:any){setError(reason.message)}finally{setWorking(false)}}
  if(loading)return <PortalShell role="admin" onLogout={logout}><Busy label="Loading candidate evidence…"/></PortalShell>;
  const whatsapp=candidateWhatsAppUrl(data?.candidate||{},data?.invitation);
  return <PortalShell role="admin" onLogout={logout}><div className="portal-header"><div><Link href="/admin" className="section-kicker"><ArrowLeft size={13}/> Candidate hierarchy</Link><h1>{data?.candidate?.fullName}<br/><span className="gradient-text">evaluation record.</span></h1><p>{data?.candidate?.email} · {data?.candidate?.phone} · {data?.candidate?.position||"Position not specified"}</p></div><div className="tool-row" style={{margin:0}}><button className="btn" onClick={()=>window.print()}><Download size={14}/>Save PDF</button>{whatsapp&&<button className="btn" onClick={()=>window.open(whatsapp,"_blank","noopener,noreferrer")}><MessageCircle size={15}/>WhatsApp</button>}<button className="btn" onClick={load}><RefreshCw size={14}/></button></div></div>{error&&<Notice kind="error">{error}</Notice>}{success&&<Notice kind="success">{success}</Notice>}
    <div className="portal-grid"><section className="panel candidate-hero"><div><StatusPill value={data?.candidate?.status}/><div className="candidate-meta"><span>Invitation: <b>{data?.invitation?.code||"—"}</b></span><span>Email: <b>{data?.invitation?.emailDelivery?.status||"—"}</b></span>{data?.resume&&<span>Resume: <b>{data.resume.originalName}</b></span>}</div></div><button className="btn" onClick={reset} disabled={working}><RotateCcw size={14}/>Reset invitation & email</button></section>
    <section className="portal-grid two"><div className="panel"><h2>AI assessment</h2><p className="panel-subtitle">{summary(data?.interview?.finalAssessment)}</p><div className="score-grid">{scores.map(([key,value])=><div className="score-box" key={key}><span>{key.replaceAll("_"," ")}</span><strong>{String(value)}{Number(value)<=100?"%":""}</strong></div>)}</div><div className="candidate-meta"><span>AI recommendation: <b>{data?.interview?.aiRecommendation?.replaceAll("_"," ")||"Pending"}</b></span><span>Integrity: <b>{data?.interview?.integrity?.label?.replaceAll("_"," ")||"Pending"}</b></span></div></div><div className="panel"><h2>Protected recording</h2><p className="panel-subtitle">Video and audio evidence are streamed only after admin authentication.</p>{media?<video className="media-player" src={media} controls playsInline/>:<Notice kind={data?.recording?.status==="READY"?"info":"error"}>{data?.recording?`Recording status: ${data.recording.status.replaceAll("_"," ")}${data.recording.lastError?` · ${data.recording.lastError}`:""}`:"No recording upload exists yet."}</Notice>}</div></section>
    <section className="panel"><h2>Question evidence</h2><div className="qa-list">{data?.questionAnswers?.map((item:any)=><article className="qa" key={item.question._id}><small>Question {item.question.sequence} · {item.question.category} · {item.question.difficulty}</small><h3>{item.question.questionText}</h3><p>{item.answer?.transcript||"No submitted answer."}</p>{item.answer?.evaluation&&<div className="candidate-meta"><span>Score: <b>{item.answer.evaluation.score??"—"}</b></span><span>Source: <b>{item.answer.source||"—"}</b></span><span>Confidence: <b>{item.answer.transcriptConfidence!==undefined?`${Math.round(item.answer.transcriptConfidence*100)}%`:"—"}</b></span></div>}</article>)}</div></section>
    <section className="portal-grid two"><div className="panel"><h2>Integrity warnings</h2><p className="panel-subtitle">Warnings are evidence for review, not an automatic rejection.</p>{data?.events?.length?<div className="qa-list">{data.events.map((event:any)=><div className="qa" key={event._id}><StatusPill value={event.type}/><p>{new Date(event.timestamp).toLocaleString("en-IN")}{event.durationMs?` · ${Math.round(event.durationMs/1000)} sec`:""}</p></div>)}</div>:<Notice kind="success">No integrity warning events were recorded.</Notice>}</div><form className="panel form-grid" onSubmit={saveDecision}><h2>Administrator decision</h2><div className="field"><label>Decision</label><select value={decision} onChange={e=>setDecision(e.target.value)}><option value="ACCEPT">Accept / Selected</option><option value="REJECT">Reject</option><option value="HOLD">Hold</option><option value="REINTERVIEW">Re-interview</option></select></div><div className="field"><label>Private admin comment</label><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Visible to administrators only"/></div><div className="field"><label>Candidate-facing feedback</label><textarea value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="This message appears in the candidate profile"/></div><button className="btn btn-primary" disabled={working||data?.interview?.status!=="COMPLETED"}>{working?"Saving…":"Save decision"}</button>{data?.interview?.status!=="COMPLETED"&&<Notice>Decision controls unlock after interview completion.</Notice>}</form></section></div>
  </PortalShell>}
