"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { Link } from "@/components/Link";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { Activity, ArrowRight, BarChart3, BrainCircuit, Building2, Check, Clock3, FileSearch, Fingerprint, Gauge, Menu, MessageSquareText, Mic2, Play, ShieldCheck, Sparkles, Star, Target, Users, Video, X, Zap } from "lucide-react";

const stats = [[Users,"10,000+","Interviews conducted"],[Building2,"500+","Companies trust us"],[Clock3,"90%","Time saved"],[Star,"4.9/5","User rating"]] as const;
const features = [[BrainCircuit,"AI-powered","Adaptive questions shaped by every answer."],[Gauge,"Scalable","Run hundreds of structured interviews in parallel."],[ShieldCheck,"Secure","Private recordings, scoped access and audit-ready evidence."],[FileSearch,"Insightful","Resume-aware scoring that shows the evidence behind decisions."]] as const;
const capabilities = [[Mic2,"Live speech capture","Voice-first answers with a manual fallback."],[Video,"Protected recording","Video and audio evidence attached to each candidate."],[Target,"Adaptive questioning","Difficulty and follow-ups respond to real performance."],[BarChart3,"Evidence scoring","Technical, behavioral and communication scorecards."],[Fingerprint,"Integrity monitoring","Actionable warnings without hidden surveillance."],[MessageSquareText,"Candidate reports","Candidates can review their own approved interview record."],[FileSearch,"Smart bulk intake","Scan spreadsheets, documents, PDFs and candidate images."],[Zap,"Automatic email","Existing invitation email flow remains built in."],[Activity,"Live admin view","Track pipeline, interview status and decisions in one place."]] as const;

function Intro({ onDone }: { onDone: () => void }) {
  const root = useRef<HTMLDivElement>(null);
  const skip = () => { if (root.current) root.current.style.display = "none"; onDone(); };
  useEffect(() => {
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches || sessionStorage.getItem("aparaitech-intro")) { onDone(); return; }
    document.body.style.overflow = "hidden";
    const mobile = window.innerWidth < 760;
    const timeline = gsap.timeline({ onComplete: onDone });
    timeline.fromTo(".intro-core", { scale:0, opacity:0 }, { scale:1, opacity:1, duration:.9, ease:"expo.out" })
      .fromTo(".intro-copy > *", { y:18, opacity:0 }, { y:0, opacity:1, stagger:.16, duration:.65 }, "-=.3")
      .to(".intro-core", { scale:mobile?5:8, opacity:.1, duration:mobile?1.6:2.3, ease:"expo.inOut" }, mobile?"+=.9":"+=1.8")
      .to(root.current, { opacity:0, duration:.7, pointerEvents:"none" }, "-=.55");
    return () => { timeline.kill(); document.body.style.overflow = ""; };
  }, [onDone]);
  return <div className="intro" ref={root}><div className="intro-grid"/><button className="intro-skip" onClick={skip}>Skip intro</button><div className="intro-core"/><div className="intro-copy"><strong>Intelligence, assembled.</strong><span>Preparing the future of hiring</span></div></div>;
}

export function LandingPage() {
  const [intro,setIntro]=useState(true); const [scrolled,setScrolled]=useState(false); const [menu,setMenu]=useState(false); const root=useRef<HTMLDivElement>(null);
  const completeIntro=useCallback(()=>{ sessionStorage.setItem("aparaitech-intro","1"); document.body.style.overflow=""; setIntro(false); },[]);
  useEffect(()=>{
    gsap.registerPlugin(ScrollTrigger);
    const onScroll=()=>setScrolled(window.scrollY>24); window.addEventListener("scroll",onScroll,{passive:true}); onScroll();
    const move=(event:MouseEvent)=>gsap.to(".cursor-glow",{x:event.clientX,y:event.clientY,duration:.8,ease:"power3.out"}); window.addEventListener("mousemove",move);
    const context=gsap.context(()=>{ gsap.utils.toArray<HTMLElement>("[data-reveal]").forEach((element)=>gsap.from(element,{y:45,opacity:0,duration:.85,ease:"power3.out",scrollTrigger:{trigger:element,start:"top 87%"}})); gsap.to(".hero-art",{yPercent:7,ease:"none",scrollTrigger:{trigger:".hero",start:"top top",end:"bottom top",scrub:true}}); },root);
    return()=>{ window.removeEventListener("scroll",onScroll); window.removeEventListener("mousemove",move); context.revert(); };
  },[]);
  return <div className="site-shell" ref={root}>{intro&&<Intro onDone={completeIntro}/>}<div className="cursor-glow"/>
    <header className={`nav ${scrolled?"scrolled":""} ${menu?"open":""}`}><div className="nav-inner"><Link className="brand" href="/"><img src="/aparaitech-logo.png" alt=""/><span>Aparaitech AI Interview<small>Intelligence for better hiring</small></span></Link><nav className="nav-links" onClick={()=>setMenu(false)}><a href="#features">Features</a><a href="#how">How it works</a><a href="#use-cases">Use cases</a><a href="#pricing">Pricing</a><a href="#resources">Resources</a></nav><div className="nav-actions"><Link className="btn btn-ghost" href="/login">Log in</Link><Link className="btn btn-primary" href="/candidate/login">Get started <ArrowRight size={14}/></Link><button className="btn icon-btn menu-btn" aria-label="Toggle menu" onClick={()=>setMenu(!menu)}>{menu?<X size={18}/>:<Menu size={18}/>}</button></div></div></header>

    <main><section className="hero"><div className="container hero-grid"><div className="hero-copy"><div className="hero-eyebrow"><i/>The future of interviews is here</div><h1>AI Interviews.<br/><span className="gradient-text">Smarter Hiring.</span><br/>Better Future.</h1><p>Our AI Interview Platform evaluates candidates fairly, intelligently and at scale. Save time, reduce bias and hire the best talent with evidence you can trust.</p><div className="hero-actions"><Link className="btn btn-primary" href="/candidate/login">Start your interview <ArrowRight size={16}/></Link><a className="btn" href="#platform"><Play size={14}/> Explore platform</a></div><div className="hero-trust"><span><i/>No credit card required</span><span><i/>Candidate-first experience</span><span><i/>Private by design</span></div></div><div className="hero-visual"><div className="hero-orbit"/><div className="hero-art"><img src="/aparaitech-ai-hero.png" alt="Futuristic Aparaitech AI interview intelligence interface"/></div><div className="float-metric metric-a"><span>Response analysis</span><strong>98%</strong><div className="metric-line"/></div><div className="float-metric metric-b"><span>Technical skills</span><strong>93%</strong><div className="metric-line"/></div></div></div></section>

    <section className="stats-wrap"><div className="container stats glass">{stats.map(([Icon,value,label])=><div className="stat" key={label}><div className="stat-icon"><Icon size={18}/></div><div><strong>{value}</strong><span>{label}</span></div></div>)}</div></section>
    <section className="section" id="platform"><div className="container platform"><div data-reveal><div className="section-kicker">AI-powered platform</div><h2 className="section-title">Interviews that <span className="gradient-text">understand more.</span></h2><p className="section-copy">Our AI evaluates not just answers, but also communication, problem solving, confidence and technical skills to give you holistic insights.</p><div className="check-list"><span><Check size={15}/>Real-time AI questioning</span><span><Check size={15}/>In-depth candidate evaluation</span><span><Check size={15}/>Evidence-based scoring</span><span><Check size={15}/>Detailed reports and insights</span></div><Link className="btn" href="/admin/login">Open admin workspace <ArrowRight size={14}/></Link></div><div className="dashboard-mock glass" data-reveal><div className="mock-top"><span>APARAITECH / FRONTEND DEVELOPER INTERVIEW</span><span className="recording-dot"><i/> REC</span></div><div className="mock-body"><div className="mock-side"><span>Dashboard</span><span className="active">Interview</span><span>Analytics</span><span>Reports</span></div><div className="mock-main"><div className="mock-question"><small>QUESTION 04 · TECHNICAL</small><br/>Explain the concept of a Virtual DOM and how it improves rendering performance.</div><div className="wave">{Array.from({length:58},(_,i)=><i key={i} style={{animationDelay:`-${(i%11)*.08}s`,height:`${18+(i*17)%68}px`}}/>)}</div><div className="score-row"><div className="score-ring"/><div className="bars">{[["Communication",88],["Technical",93],["Confidence",86],["Clarity",95]].map(([label,value])=><div className="bar" key={label}><span>{label}</span><i style={{"--value":`${value}%`} as React.CSSProperties}/><b>{value}</b></div>)}</div></div></div></div></div></div></section>
    <section className="section" id="use-cases"><div className="container"><div className="section-kicker">Trusted by innovative teams</div><div className="logos">{["Google","Microsoft","Amazon","Airbnb","Netflix","Spotify"].map(name=><div className="logo-name" key={name}>{name}</div>)}</div></div></section>
    <section className="section" id="features"><div className="container"><div data-reveal><div className="section-kicker">Why choose Aparaitech</div><h2 className="section-title">Built for high-volume hiring, <span className="gradient-text">designed for humans.</span></h2></div><div className="card-grid">{features.map(([Icon,title,copy])=><article className="feature-card glass" data-reveal key={title}><Icon size={24}/><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="section" id="how"><div className="container"><div className="section-kicker">How it works</div><h2 className="section-title">From invitation to insight in <span className="gradient-text">three clear steps.</span></h2><div className="steps">{[["Invite","Add one candidate or smart-scan a bulk file. Every candidate receives their own secure code by email."],["Interview","The candidate signs in, uploads a resume and completes an adaptive video interview on web or mobile."],["Decide","Review AI scores, answers, integrity signals and the protected recording before making a decision."]].map(([title,copy])=><article className="step glass" data-reveal key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="section" id="resources"><div className="container"><div className="section-kicker">Complete interview intelligence</div><h2 className="section-title">One secure system. <span className="gradient-text">Every hiring signal.</span></h2><div className="cap-grid">{capabilities.map(([Icon,title,copy])=><article className="cap glass" data-reveal key={title}><div className="cap-icon"><Icon size={18}/></div><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></div></section>
    <section className="section" id="pricing"><div className="container final-cta glass" data-reveal><Sparkles size={28}/><h2>Ready to make every interview count?</h2><p>Candidate access is invitation-based. Administrators can sign in to manage the complete hiring workflow.</p><div className="hero-actions" style={{justifyContent:"center"}}><Link className="btn btn-primary" href="/candidate/login">Use invitation code <ArrowRight size={15}/></Link><Link className="btn" href="/admin/login">Administrator login</Link></div></div></section></main>
    <footer className="footer"><div className="container"><div className="footer-grid"><div><Link className="brand" href="/"><img src="/aparaitech-logo.png" alt=""/><span>Aparaitech AI Interview</span></Link><p>Evidence-rich AI interviews for fairer, faster and more confident hiring.</p></div><div><h4>Platform</h4><a href="#features">Features</a><a href="#how">How it works</a><Link href="/candidate/login">Candidate access</Link></div><div><h4>Workspace</h4><Link href="/admin/login">Admin login</Link><a href="#resources">Resources</a><a href="#use-cases">Use cases</a></div><div><h4>Standards</h4><a href="#platform">Private by design</a><a href="#platform">Evidence based</a><a href="#platform">Candidate first</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Aparaitech Software Team</span><span>AI Interviews · Smarter Hiring · Better Future</span></div></div></footer>
  </div>;
}
