export const QUESTION_CATEGORIES = ["INTRODUCTION", "RESUME", "TECHNICAL", "PROJECT", "APTITUDE", "PROBLEM_SOLVING", "COMMUNICATION", "BEHAVIORAL", "SITUATIONAL", "ROLE_SPECIFIC", "FOLLOW_UP"];
export const DIFFICULTIES = ["EASY", "MEDIUM", "HARD"];
export const EVENT_TYPES = ["FACE_MISSING", "MULTIPLE_FACES", "FACE_OUT_OF_FRAME", "FACE_TOO_FAR", "FACE_TOO_CLOSE", "GAZE_DEVIATION", "APP_BACKGROUND", "BACK_BUTTON_ATTEMPT", "MIC_INTERRUPTION", "CAMERA_INTERRUPTION", "RECORDING_INTERRUPTION", "NETWORK_INTERRUPTION", "SESSION_RECOVERED", "ADMIN_TERMINATED"];
export const DECISIONS = ["ACCEPT", "REJECT", "HOLD", "REINTERVIEW"];
export const RECOMMENDATIONS = ["STRONGLY_QUALIFY", "QUALIFY", "BORDERLINE", "REVIEW_REQUIRED", "NOT_RECOMMENDED"];
