"use client";
import { ChangeEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ArrowRight, FileUp, RefreshCw, Video } from "lucide-react";
import { api } from "@/lib/api";
import { session } from "@/lib/session";
import { Busy, Notice, PortalShell, StatusPill } from "@/components/portal/PortalShell";

function assessmentText(value:any):string { if(!value)return "Your AI assessment will appear after the interview is completed."; if(typeof value==="string")return value; return value.summary||value.overallSummary||value.recommendationRationale||Object.values(value).filter(item=>typeof item==="string").join(" ")||"Assessment complete."; }
export default function CandidateProfile(){const [data,setData]=useState<any>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(true);const [uploading,setUploading]=useState(false);const [media,setMedia]=useState("");
  const logout=()=>{session.clearCandidate();window.location.replace("/candidate/login")};
  const load=useCallback(async()=>{if(!session.get("status")){window.location.replace("/candidate/login");return}setBusy(true);setError("");try{setData(await api.candidateProfile())}catch(reason:any){if(reason.status===401)logout();else setError(reason.message)}finally{setBusy(false)}},[]);
  useEffect(()=>{load()},[load]);
  useEffect(()=>{let objectUrl="";(async()=>{if(data?.recording?.status==="READY"&&data?.interview?.id){try{objectUrl=await api.protectedMedia(`/api/candidates/me/interviews/${data.interview.id}/recording`,session.get("status"));setMedia(objectUrl)}catch{}}})();return()=>{if(objectUrl)URL.revokeObjectURL(objectUrl)}},[data?.recording?.status,data?.interview?.id]);
  async function resume(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setUploading(true);setError("");try{await api.uploadResume(data.candidate.id,file);await load()}catch(reason:any){setError(reason.message)}finally{setUploading(false);event.target.value=""}}
  const scores=useMemo(()=>Object.entries(data?.interview?.scores||{}).filter(([,value])=>typeof value==="number"),[data]);
  if(busy)return <PortalShell role="candidate" onLogout={logout}><Busy label="Loading your private interview profile…"/></PortalShell>;
  return <PortalShell role="candidate" onLogout={logout}><div className="portal-header"><div><span className="section-kicker">Private candidate profile</span><h1>{data?.candidate?.fullName||"Candidate"}<br/><span className="gradient-text">interview record.</span></h1><p>Your data is visible only to you and authorized administrators.</p></div><button className="btn" onClick={load}><RefreshCw size={15}/>Refresh</button></div>{error&&<Notice kind="error">{error}</Notice>}
    <div className="portal-grid" style={{gap:18}}><section className="panel candidate-hero"><div><StatusPill value={data?.candidate?.status}/><div className="candidate-meta"><span>{data?.candidate?.email}</span><span>{data?.candidate?.phone}</span>{data?.candidate?.position&&<span>{data.candidate.position}</span>}{data?.candidate?.college&&<span>{data.candidate.college}</span>}</div></div><div>{(!data?.resume||data?.resume?.parseStatus==="FAILED")&&<label className="btn btn-primary" style={{cursor:"pointer"}}><FileUp size={16}/>{uploading?"Processing resume…":"Upload resume"}<input hidden type="file" accept=".pdf,.doc,.docx,image/jpeg,image/png,image/webp" onChange={resume} disabled={uploading}/></label>}{data?.resume&&data?.candidate?.status!=="INTERVIEW_COMPLETED"&&!data?.candidate?.status?.match(/SELECTED|REJECTED/)&&<a className="btn btn-primary" href="/candidate/interview">{data.candidate.status==="INTERVIEW_IN_PROGRESS"?"Continue interview":"Start web interview"}<ArrowRight size={16}/></a>}</div></section>
    {!data?.resume&&<Notice>Upload your resume first. When secure processing completes, the interview button will become available.</Notice>}{data?.resume?.parseStatus==="PENDING"&&<Notice>Resume processing is in progress. Refresh this page in a moment.</Notice>}
    {data?.interview&&<><section className="panel"><h2>AI interview summary</h2><p className="panel-subtitle">{assessmentText(data.interview.finalAssessment)}</p><div className="score-grid">{scores.length?scores.map(([key,value])=><div className="score-box" key={key}><span>{key.replaceAll("_"," ")}</span><strong>{String(value)}{Number(value)<=100?"%":""}</strong></div>):<div className="score-box"><span>Interview status</span><strong style={{fontSize:17}}>{String(data.interview.status).replaceAll("_"," ")}</strong></div>}</div><div className="candidate-meta"><span>AI recommendation: <b>{data.interview.aiRecommendation?.replaceAll("_"," ")||"Pending"}</b></span>{data.interview.integrity?.label&&<span>Integrity: <b>{data.interview.integrity.label.replaceAll("_"," ")}</b></span>}</div></section>
      <section className="portal-grid two"><div className="panel"><h2>Interview recording</h2><p className="panel-subtitle">Your complete video includes recorded audio. It is protected and is never exposed as a public URL.</p>{media?<video className="media-player" src={media} controls playsInline/>:<Notice>{data.recording?.status==="READY"?"Loading protected recording…":data.recording?.status?`Recording status: ${data.recording.status.replaceAll("_"," ")}`:"Recording is not available yet."}</Notice>}</div><div className="panel"><h2>Administrator decision</h2>{data.decision?<><StatusPill value={data.decision.decision}/><p className="panel-subtitle" style={{marginTop:18}}>{data.decision.candidateFeedback||"No candidate feedback was added."}</p></>:<Notice>Your result is still under review. You will see candidate-facing feedback here when an administrator completes the decision.</Notice>}</div></section>
      <section className="panel"><h2>Question and answer evidence</h2><p className="panel-subtitle">This is the same submitted answer evidence available to the authorized reviewer.</p><div className="qa-list">{data.questionAnswers?.map((item:any)=><article className="qa" key={item.question.id}><small>Question {item.question.sequence} · {item.question.category} · {item.question.difficulty}</small><h3>{item.question.text}</h3><p>{item.answer?.transcript||"No answer was recorded."}</p>{item.answer?.evaluation?.score!==undefined&&<StatusPill value={`Score ${item.answer.evaluation.score}`}/>}</article>)}</div></section></>}
    </div></PortalShell>}
